name: Keep docs manifest up to date
on:
  pull_request:
    branches:
      - trunk
    paths:
      - docs/**

jobs:
  check-docs-manifest:
    name: Check docs manifest for staleness
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Regenerate manifest
      run: composer run docs:manifest

    - name: Check whether manifest has been updated
      env:
        MANIFEST_PATH: docs/bin/manifest.json
      run: |
        if ! git diff --quiet -- "$MANIFEST_PATH"; then
          echo "There are documentation changes in this branch that require that the docs manifest be regenerated."
          echo
          echo "Please run 'composer run docs:manifest' and commit $MANIFEST_PATH"
          exit 1
        fi
