name: JavaScript Unit Tests

on:
    pull_request:
        branches: [trunk]
    push:
        branches: [trunk]
    # Allow manually triggering the workflow
    workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default
permissions: {}

jobs:
    unit-js:
        name: Node.js ${{ matrix.node }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
        strategy:
            fail-fast: false
            matrix:
                event: ['${{ github.event_name }}']
                node: ['20', '22', '24']
                exclude:
                    # On PRs: only test minimum supported version
                    - event: 'pull_request'
                      node: '22'
                    - event: 'pull_request'
                      node: '24'

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  show-progress: false
                  persist-credentials: false

            - name: Setup Node.js and install dependencies
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: ${{ matrix.node }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run JavaScript unit tests
              run: npm run test:unit -- --ci
